title: Stop The Slop
description: A manifesto for genuine design and engineering. Championing craftsmanship over "slop".
url: "https://stoptheslop.github.io"
author:
  name: Stop The Slop Community
twitter:
  username: stoptheslop

plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag

collections:
  signatures:
    output: true

pagination:
  enabled: true
  collection: signatures
  per_page: 10
  permalink: "/page:num/"
  sort_field: "date"
  sort_reverse: true
